//! WIT contract crate for savvagent external plugins (sub-project D).
//!
//! This crate is intentionally a documentation-and-resources leaf: it owns
//! the `.wit` files that describe the three external-plugin worlds
//! (`plugin-static`, `plugin-interactive`, `plugin-provider`) and ships
//! them as crate-relative resources for downstream consumers.
//!
//! ## Why no `wit_bindgen::generate!` here
//!
//! `wit-bindgen` is a *guest*-side code generator: it produces the bindings
//! a WASM component links against to satisfy its imports/exports. Plugin
//! authors depend on `wit-bindgen` from their own crate; this crate would
//! gain nothing by invoking the macro on the host build.
//!
//! Host-side bindings (the types and `bindgen!`-generated traits the host
//! linker uses to satisfy a component's imports) live in
//! `savvagent-plugin-wasm` (Task 2), generated by
//! `wasmtime::component::bindgen!` against the `.wit` files in this crate.
//! That keeps wasmtime, tokio, reqwest, and the rest of the runtime out of
//! this crate — see `.github/workflows/wit-dep-guard.yml`.
//!
//! ## Where to find things
//!
//! - `wit/shared.wit` — shared interface (effects, manifest, hook kinds,
//!   key events, theme colors, styled spans, errors).
//! - `wit/spp.wit` — SPP types mirroring `savvagent-protocol`
//!   (CompleteRequest/Response, streaming events, provider errors).
//! - `wit/plugin-static.wit`, `wit/plugin-interactive.wit`,
//!   `wit/plugin-provider.wit` — the three plugin worlds (skeletons in
//!   Task 1; filled in Task 2).

#![forbid(unsafe_code)]

// The `.wit` files in `../wit/` are the canonical source of truth for this
// crate. They are not included as rustdoc via `include_str!` because raw
// WIT contains indented blocks that rustdoc would parse as Rust doctests
// and reject. Browse the files directly under
// `crates/savvagent-plugin-wit/wit/`.

/// Absolute path to this crate's `wit/` directory, resolved at the time
/// **this crate** is compiled (`CARGO_MANIFEST_DIR` is set by Cargo).
///
/// Intended for `build.rs` scripts in downstream crates that need to read
/// the canonical WIT source — e.g. to copy it into `OUT_DIR` or feed it
/// to `wit-parser` at consuming-crate build time.
///
/// **Not** usable inside proc-macro `path: "…"` arguments such as
/// `wasmtime::component::bindgen!`: those require string literals at the
/// macro callsite and cannot read a `const &str` from a dependency at
/// expansion time. Downstream macro callers must pass a string literal
/// such as `path: "../savvagent-plugin-wit/wit"`.
pub const WIT_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/wit");
